jwt:
  access:
  
    secret: "yeonjin-inspire-project-secret-key-2026-fighting-fighting"
    expires: 1800000  
  refresh:
    secret: "yeonjin-inspire-project-refresh-key-2026-fighting-fighting"
    expires: 1209600000 