spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_ROOT_USERNAME}
    password: ${DB_ROOT_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
      pool-name: hikari_primary_pool

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

    properties:
      hibernate:
        format-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

server:
  port: 8443

  ssl:
    enabled: true
    key-store: /certs/keystore.p12
    key-store-type: PKCS12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-alias: ${SSL_KEY_ALIAS}

front:
  redirect:
    url: "http://localhost:3000"

cookie:
  policy:
    samesite: None
    secure: true