spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MariaDB;DATABASE_TO_LOWER=true
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
      pool-name: hikari_primary_pool

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

management:
  health:
    redis:
      enabled: false

server:
  port: 8443
  ssl:
    enabled: true
    key-store: /certs/keystore.p12
    key-store-type: PKCS12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-alias: ${SSL_KEY_ALIAS}

front:
  redirect:
    url: "http://localhost:3000"